name: Publish

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish:
    name: Publish extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24.x

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Publish to Open VSX Registry
        id: publish-to-open-vsx
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OVSX_TOKEN }}
          packagePath: './'

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publish-to-open-vsx.outputs.vsixPath }}

      - name: Attach VSIX to GitHub release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: '*.vsix'
